#!/bin/sh
# Get uptime value in seconds in busybox
uptime_sec="$(printf "%0.10d\n" "$(cat /proc/uptime | cut -d"." -f1)")"

echo "Status: 200 OK"
echo "Content-Type: application/json"
echo ""
cat <<EOF
{
    "status": "OK",
    "name": "${HOSTNAME}",
    "version": "${IMAGE_VERSION}",
    "timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%S")",
    "uptime": "${uptime_sec}"
}
EOF
echo ""
echo ""
